$script_mysql = <<-SCRIPT
    sudo apt-get update && \
    sudo apt-get install -y mysql-server-5.7 && \
    sudo mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network "forwarded_port", guest: 80, host: 8089
	config.vm.network "private_network", ip: "172.0.1.100"

	config.vm.provision "shell", 
		inline: "cat /configs/id_rsa.pub >> .ssh/authorized_keys"
	config.vm.provision "shell", 
		inline: $script_mysql
	config.vm.provision "shell",
        inline: "sudo cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    config.vm.provision "shell",
        inline: "sudo service mysql restart"

	config.vm.synced_folder "./configs", "/configs"
	config.vm.synced_folder ".", "/vagrant", disabled: true
end