$script_mysql = <<-SCRIPT
    sudo apt-get update && \
    sudo apt-get install -y mysql-server-5.7 && \
    sudo mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/bionic64"

	config.vm.define "mysqldb" do |mysql|
		mysql.vm.network "private_network", ip: "172.0.1.100"

		mysql.vm.provision "shell", 
			inline: "cat /configs/id_rsa.pub >> .ssh/authorized_keys"
		mysql.vm.provision "shell", 
			inline: $script_mysql
		mysql.vm.provision "shell",
        	inline: "sudo cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
		mysql.vm.provision "shell",
        	inline: "sudo service mysql restart"

		mysql.vm.synced_folder "./configs", "/configs"
		mysql.vm.synced_folder ".", "/vagrant", disabled: true
	end

	config.vm.define "phpweb" do |php|
		php.vm.network "forwarded_port", guest: 80, host: 8089
		php.vm.network "private_network", ip: "172.0.1.101"

		php.vm.provision "shell",
        	inline: "sudo apt-get update && sudo apt-get install -y puppet"
			php.vm.provision "puppet" do |puppet|
			puppet.manifests_path = "./configs/manifest"
			puppet.manifest_file = "phpweb.pp"
		end
	end
end